/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: Anthony <Anthony@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/04/01 09:21:10 by alevasse          #+#    #+#             */
/*   Updated: 2022/04/03 20:46:48 by Anthony          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>
#include "ft_printf.h"

int	main()
{
	int		i;

	printf("---------------------- CHAR ----------------------------- \n");
	ft_putchar('\n');
	printf ("prin: %c %c \n", 'a', 65);
	ft_printf("mine: %c %c \n", 'a', 65);
	ft_putchar('\n');
	printf ("prin: %c \n", 'a');
	ft_printf("mine: %c \n", 'a');
	ft_putchar('\n');
	printf("prin: %5c\n", '$');
	ft_printf("mine: %5c\n", '$');
	ft_putchar('\n');
	printf("prin: %10c\n", '$');
	ft_printf("mine: %10c\n", '$');
	ft_putchar('\n');
	printf("prin minus: %-5c %c\n", '$', '%');
	ft_printf("mine minus: %-5c %c\n", '$', '%');
	ft_putchar('\n');
	//Check for null character
	i = printf("|%c|\n", '\0');
	printf("Return value: %d\n", i);
	i = ft_printf("|%c|\n", '\0');
	printf("Return value: %d\n", i);
	ft_putchar('\n');
	ft_putchar('\n');

	printf("----------- Char 42FC--------------- \n");
	ft_putchar('\n');
	printf("pf: %5c\n", 42); 
	ft_printf("me: %5c\n", 42);
	ft_putchar('\n');
	printf("pf: %-5c\n", 42); 
	ft_printf("me: %-5c\n", 42);                        
	ft_putchar('\n');
	printf("pf: %c\n", 0);  
	ft_printf("me: %c\n", 0);               
	ft_putchar('\n');
	printf("pf: %2c\n", 0);  
	ft_printf("me: %2c\n", 0);
	ft_putchar('\n'); 
	printf("pf: %5c\n", 42);
	ft_printf("me: %5c\n", 42);
	ft_putchar('\n'); 
	printf("%-5c\n", 42);
	ft_printf("%-5c\n", 42);                          
	ft_putchar('\n');
	ft_putchar('\n');

	printf("---------------------- STRINGS ----------------------------- \n");
	ft_putchar('\n');
	printf ("pf a simple string: %s \n", "A string");
	ft_printf ("me a simple string: %s \n", "A string");
	ft_putchar('\n');
	printf ("pf prec test: %.5s \n", "abcdefg");
	ft_printf ("me prec test: %.5s \n", "abcdefg");
	ft_putchar('\n');
	printf ("pf prec and right pad: %-10.5s %c\n", "abcdefg", 's');
	ft_printf ("me prec and right pad: %-10.5s %c\n", "abcdefg", 's');
	ft_putchar('\n');
	printf ("pf 10 pad: %10s \n", "abcdefg");
	ft_printf ("me 10 pad: %10s \n", "abcdefg");
	ft_putchar('\n');
	printf ("pf string minus pad: %-10s%c\n", "A string",'c');
	ft_printf ("me string minus pad: %-10s%c\n", "A string",'c');
	ft_putchar('\n');
	printf("pf: hello, %s \n" , "gavin");
	ft_printf("me: hello, %s \n" , "gavin");
	//NULL Character check
	i = printf("|%s|\n", "\0");
	printf("Return value: %d\n", i);
	i = ft_printf("|%s|\n", "\0");
	ft_printf("Return value: %d\n", i);
	ft_putchar('\n');
	
	printf("----------- String 42FC--------------- \n");
	ft_putchar('\n');
	printf("pf: %10s is a string\n", "this");
	ft_printf("me: %10s is a string\n", "this");
	ft_putchar('\n');
	printf("pf: %.2s is a string\n", "this");
	ft_printf("me: %.2s is a string\n", "this");
	ft_putchar('\n');
	printf("pf: %5.2s is a string\n", "this");
	ft_printf("me: %5.2s is a string\n", "this");
	ft_putchar('\n');
	printf("pf: %10s is a string\n", "");
  	ft_printf("me: %10s is a string\n", "");
	ft_putchar('\n');
	printf("pf: %10s is a string\n", "this");
	ft_printf("me: %10s is a string\n", "this");
	ft_putchar('\n');
	printf("pf: %-10s is a string\n", "this");
	ft_printf("me: %-10s is a string\n", "this");
	ft_putchar('\n');
	printf("pf minus 10: %-10s is a string\n", "this");
	ft_printf("me minus 10: %-10s is a string\n", "this");
	ft_putchar('\n');	
	printf("pf: %.2s is a string\n", "this");
	ft_printf("me: %.2s is a string\n", "this");
	ft_putchar('\n');
	printf("pf: %5.2s is a string\n", "this");
	ft_printf("me: %5.2s is a string\n", "this");
	ft_putchar('\n');
	printf("pf: %s %s\n", NULL, "string");
	ft_printf("me: %s %s\n", NULL, "string");
	ft_putchar('\n');
	ft_putchar('\n');

	
	printf("---------------------- I & D ----------------------------- \n");
	ft_putchar('\n');
	printf("pf: %i, %i\n", 42, 21);
	ft_printf("me: %i, %i\n", 42, 21);
	ft_putchar('\n');
	printf("pf: %i\n", -42);
	ft_printf("me: %i\n", -42);
	ft_putchar('\n');
	printf("pf: %i, %i, %i\n", 42, -21, 69); 
	ft_printf("me: %i, %i, %i\n", 42, -21, 69);
	ft_putchar('\n');
	printf("pf: %03i\n", 1993);
	ft_printf("pf: %.3i\n", 1993);
	ft_putchar('\n');
	printf("pf: %.3i\n", -1993);
	ft_printf("pf: %.3i\n", -1993);
	ft_putchar('\n');
	printf("pf: %.3i\n", -696969);
	ft_printf("pf: %.3i\n", -696969);
	ft_putchar('\n');
	printf ("pf preceding with blanks: %10i \n", 1977);
	ft_printf("me preceding with blanks: %10i \n", 1977);
	ft_putchar('\n');
	printf ("pf: %10i \n", -1977);
	ft_printf("me: %10i \n", -1977);
	ft_putchar('\n');
	printf ("pf: %-10i \n", 1977);
	ft_printf("me: %-10i \n", 1977);
	ft_putchar('\n');
	printf ("pf: %-10i \n", -1977);
	ft_printf("me: %-10i \n", -1977);
	ft_putchar('\n');
	printf ("pf plus flag: %+i \n", 1977);
	ft_printf("me plus flag: %+i \n", 1977);
	ft_putchar('\n');
	printf ("pf plus flag: %+10i \n", 1977);
	ft_printf("me plus flag: %+10i \n", 1977);
	ft_putchar('\n');
	printf ("pf preceding with zeros: %010i \n", 1977);
	ft_printf("me preceding with zeros: %010i \n", 1977);
	ft_putchar('\n');
	printf("pf prec: %.6i\n", 1993);
	ft_printf("me prec: %.6i\n", 1993);
	ft_putchar('\n');
	printf("pf space f: %  i\n", 5000);
	ft_printf("me space f: %  i\n", 5000);
	ft_putchar('\n');
	ft_putchar('\n');

	printf("pf: %d, %d\n", 42, 21);
	ft_printf("me: %d, %d\n", 42, 21);
	ft_putchar('\n');
	printf("pf: %d\n", -42);
	ft_printf("me: %d\n", -42);
	ft_putchar('\n');
	printf("pf: %d, %d, %d\n", 42, -21, 69); 
	ft_printf("me: %d, %d, %d\n", 42, -21, 69);
	ft_putchar('\n');
	printf("pf: %03d\n", 1993);
	ft_printf("pf: %03d\n", 1993);
	ft_putchar('\n');
	printf("pf: %.3d\n", -1993);
	ft_printf("pf: %.3d\n", -1993);
	ft_putchar('\n');
	printf ("pf d and ld: %d %ld\n", 1977, 650000L);
	ft_printf ("me d and ld: %d %ld\n", 1977, 650000L);
	ft_putchar('\n');
	printf ("pf preceding with blanks: %10d \n", 1977);
	ft_printf("me preceding with blanks: %10d \n", 1977);
	ft_putchar('\n');
	printf ("pf: %10d \n", -1977);
	ft_printf("me: %10d \n", -1977);
	ft_putchar('\n');
	printf ("pf: %-10d \n", 1977);
	ft_printf("me: %-10d \n", 1977);
	ft_putchar('\n');
	printf ("pf: %-10d \n", -1977);
	ft_printf("me: %-10d \n", -1977);
	ft_putchar('\n');
	printf ("pf plus flag: %+i \n", 1977);
	ft_printf("me plus flag: %+i \n", 1977);
	ft_putchar('\n');
	printf ("pf plus flag: %+10d \n", 1977);
	ft_printf("me plus flag: %+10d \n", 1977);
	ft_putchar('\n');
	printf ("pf preceding with zeros: %010d \n", 1977);
	ft_printf("me preceding with zeros: %010d \n", 1977);
	ft_putchar('\n');
	printf("pf prec: %.6d\n", 1993);
	ft_printf("me prec: %.6d\n", 1993);
	ft_putchar('\n');
	printf("pf prec: %.6d\n", 93);
	ft_printf("me prec: %.6d\n", 93);
	ft_putchar('\n');
	printf("pf prec: %.0d\n", 93);
	ft_printf("me prec: %.0d\n", 93);
	ft_putchar('\n');
	printf("pf prec: %.6d\n", 5000);
	ft_printf("me prec: %.6d\n", 5000);
	ft_putchar('\n');
	printf("pf space f: % d\n", 5000);
	ft_printf("me space f: % d\n", 5000);
	ft_putchar('\n');
	ft_putchar('\n');

	printf("----------- D&I 42FC--------------- \n");
	ft_putchar('\n');
	printf("pf: %5d\n", -42);
	ft_printf("me: %5d\n", -42);
	ft_putchar('\n');
	printf("pf: %05d\n", -42);
	ft_printf("me: %05d\n", -42);
	ft_putchar('\n');
	printf("pf space -42: % d\n", -42);
	ft_printf("me space -42: % d\n", -42);
	ft_putchar('\n');
	printf("pf plus -42: %+d\n", -42);
	ft_printf("me plus -42: %+d\n", -42);
	ft_putchar('\n');
	printf("pf zero + 42: %0+5d\n", 42);
	ft_printf("me zero + 42: %0+5d\n", 42);
	ft_putchar('\n');
	printf("pf 0 5 -42: %05d\n", -42);
	ft_printf("me 0 5 -42: %05d\n", -42);
	ft_putchar('\n');
	printf("pf 0 + 5 -42: %0+5d\n", -42);
	ft_printf("me 0 + 5 -42: %0+5d\n", -42);
	ft_putchar('\n');
	printf("pf: %4.15d\n", 42); 
	ft_printf("me: %4.15d\n", 42);
	ft_putchar('\n');
	i = printf("pf: % 10.5d\n", 4242);
	printf("%d\n", i);
	i = ft_printf("me: % 10.5d\n", 4242);
	ft_printf("%d\n", i);
	ft_putchar('\n');
	printf("pf: %+10.5d\n", 4242);       
	ft_printf("me: %+10.5d\n", 4242);                   
	ft_putchar('\n');
	printf("pf: %-+10.5d\n", 4242);  
	ft_printf("me: %-+10.5d\n", 4242);                  
	ft_putchar('\n');
	i = printf("pf: %03.2d\n", 0);
	printf("%d\n", i);
	i =ft_printf("me: %03.2d\n", 0);
	ft_printf("%d\n", i);
	ft_putchar('\n');
	i = printf("pf: %03.2d\n", 1);
	printf("%d\n", i);
	i = ft_printf("me: %03.2d\n", 1);
	ft_printf("%d\n", i);
	ft_putchar('\n');
	printf("pf: %03.2d\n", -1);
	ft_printf("me: %03.2d\n", -1);
	ft_putchar('\n');
	i = printf("pf: %.d %.0d\n", 0, 0);
	printf("%d\n", i);
	i = ft_printf("me: %.d %.0d\n", 0, 0);
	ft_printf("%d\n", i);
	ft_putchar('\n');
	i = printf("pf: %5.d %5.0d\n", 0, 0);
	printf("%d\n", i);
 	i = ft_printf("me: %5.d %5.0d\n", 0, 0);
	ft_printf("%d\n", i);
	ft_putchar('\n');
	printf("pf: % d\n", -42);      
	ft_printf("me: % d\n", -42);                        
	ft_putchar('\n');
	printf("pf: %+d\n", -42);    
 	ft_printf("me: %+d\n", -42);                          
	ft_putchar('\n');
	printf("pf: %.10d\n", -42);
	ft_printf("me: %.10d\n", -42);
	ft_putchar('\n');
	printf("pf: %.10d\n", 42);
	ft_printf("me: %.10d\n", 42);
	ft_putchar('\n');
	ft_putchar('\n');

	printf("---------------------- HEX ----------------------------- \n");
	ft_putchar('\n');
	printf("pf: %-7x %c\n", 1600, '.');
	ft_printf("me: %-7x %c\n", 1600, '.');
	ft_putchar('\n');
	printf("pf prec 7: %.7x \n", 1600);
	ft_printf("me prec 7: %.7x \n", 1600);
	ft_putchar('\n');
	printf("pf prec 5: %.5x \n", 2);
	ft_printf("me prec 5: %.5x \n", 2);
	ft_putchar('\n');
	printf("pf prec hash: %.4x \n", 20);
	ft_printf("me prec hash: %.4x \n", 20);
	ft_putchar('\n');
	printf("pf prec hash: %#.7x \n", 1600);
	ft_printf("me prec hash: %#.7x \n", 1600);
	ft_putchar('\n');
	printf("pf prec hash: %#.5x \n", 2);
	ft_printf("me prec hash: %#.5x \n", 2);
	ft_putchar('\n');
	printf("pf: %-5x %c \n", 1600, '.');
	ft_printf("me: %-5x %c \n", 1600, '.');
	ft_putchar('\n');
	printf("pf: %#x \n", 1600);
	ft_printf("me: %#x \n", 1600);
	ft_putchar('\n');
	printf("pf: %#-x \n", 1600);
	ft_printf("me: %#-x \n", 1600);
	ft_putchar('\n');
	printf("pf just zeros: %010x\n", 7);
	ft_printf("me just zeros: %010x\n", 7);
	ft_putchar('\n');
	printf("pf pre 0x str: 0x%08x\n", 7);
	ft_printf("me pre 0x str: 0x%08x\n", 7);
	ft_putchar('\n');
	printf("pf: %#010x\n", 7);
	ft_printf("me: %#010x\n", 7);
	ft_putchar('\n');
	printf("pf: %#08x\n", 7);
	ft_printf("me: %#08x\n", 7);
	ft_putchar('\n');
	ft_putchar('\n');

	printf("----------- HEX 42FC--------------- \n");
	ft_putchar('\n');
	i = printf("pf #08: %#08x %c\n", 42, '.');
	printf("%d\n", i);
	i = ft_printf("me #08: %#08x %c\n", 42, '.');
	printf("%d\n", i);
	ft_putchar('\n');
	i = printf("pf hash and padding:%#8x\n", 42);
	printf("%d\n", i);
	i =ft_printf("me hash and padding:%#8x\n", 42);
	ft_printf("%d\n", i);
	ft_putchar('\n');
	i = printf("pf -42 :%x\n", -42);
	printf("%d\n", i);
	i = ft_printf("me -42 :%x\n", -42);
	ft_printf("%d\n", i);
	ft_putchar('\n');
	printf("pf #0: %#x\n", 0);
	ft_printf("me #0: %#x\n", 0);
	ft_putchar('\n');
	i = printf("pf not fine: %#.x %#.0x\n", 0, 0);
	printf("%d\n", i);
	i = ft_printf("me not fine: %#.x %#.0x\n", 0, 0);
	ft_printf("%d\n", i);
	ft_putchar('\n');
	i = printf("pf not fine: %.x %.0x\n", 0, 0);
	printf("%d\n", i);
	i = ft_printf("me not fine: %.x %.0x\n", 0, 0);
	ft_printf("%d\n", i);
	ft_putchar('\n');
	i = printf("pf fine: %5.x %5.0x\n", 0, 0);
	printf("%d\n", i);
	i = ft_printf("me fine: %5.x %5.0x\n", 0, 0);
	ft_printf("%d\n", i);
	ft_putchar('\n');
	ft_putchar('\n');

	printf("---------------------- UPPER HEX ----------------------------- \n");
	ft_putchar('\n');
	printf("pf: %-7X %c\n", 1600, '.');
	ft_printf("me: %-7X %c\n", 1600, '.');
	ft_putchar('\n');
	printf("pf prec 7: %.7X \n", 1600);
	ft_printf("me prec 7: %.7X \n", 1600);
	ft_putchar('\n');
	printf("pf prec 5: %.5X \n", 2);
	ft_printf("me prec 5: %.5X \n", 2);
	ft_putchar('\n');
	printf("pf prec hash: %.4X \n", 20);
	ft_printf("me prec hash: %.4X \n", 20);
	ft_putchar('\n');
	printf("pf prec hash: %#.7X \n", 1600);
	ft_printf("me prec hash: %#.7X \n", 1600);
	ft_putchar('\n');
	printf("pf prec hash: %#.5X \n", 2);
	ft_printf("me prec hash: %#.5X \n", 2);
	ft_putchar('\n');
	printf("pf: %-5X %c \n", 1600, '.');
	ft_printf("me: %-5X %c \n", 1600, '.');
	ft_putchar('\n');
	printf("pf: %#X \n", 1600);
	ft_printf("me: %#X \n", 1600);
	ft_putchar('\n');
	printf("pf: %#-X \n", 1600);
	ft_printf("me: %#-X \n", 1600);
	ft_putchar('\n');
	printf("pf just zeros: %010X\n", 7);
	ft_printf("me just zeros: %010X\n", 7);
	ft_putchar('\n');
	printf("pf pre 0x str: 0x%08X\n", 7);
	ft_printf("me pre 0x str: 0x%08X\n", 7);
	ft_putchar('\n');
	printf("pf: %#010X\n", 7);
	ft_printf("me: %#010X\n", 7);
	ft_putchar('\n');
	printf("pf: %#08X\n", 7);
	ft_printf("me: %#08X\n", 7);
	ft_putchar('\n');
	ft_putchar('\n');

	printf("----------- Upper Hex 42FC--------------- \n");
	ft_putchar('\n');
	printf("%X\n", 42);
	ft_printf("%X\n", 42);
	ft_putchar('\n');
	printf("%X\n", -42);
	ft_printf("%X\n", -42);
	ft_putchar('\n');
	ft_putchar('\n');

	
	printf("---------------------- PERCENT ----------------------------- \n");
	ft_putchar('\n');
	printf("pf percent: %%\n");
	ft_printf("me percent: %%\n");
	ft_putchar('\n');
	i = printf("pf: %5%\n");
	printf("%d\n", i);
	i = ft_printf("me: %5%\n");
	ft_printf("%d\n", i);
	ft_putchar('\n');
	i = printf("pf: %-5% %c\n", '.');
	printf("%d\n", i);
	i = ft_printf("me: %-5% %c\n", '.');
	ft_printf("%d\n", i);
	ft_putchar('\n');
	ft_putchar('\n');
	

	printf("---------------------- POINTER ----------------------------- \n");
	ft_putchar('\n');
	int a = 42;
	printf("The address of a is: %p\n", (void *) &a);
	ft_printf("The address of a is: %p\n", (void *) &a);
	ft_putchar('\n');
	printf("conversion of 42: %p\n", (void *) 42);
	ft_printf("conversion of 42: %p\n", (void *) 42);
	ft_putchar('\n');
	printf("conversion of null: %p\n", (void *) NULL);
	ft_printf("conversion of null: %p\n", (void *) NULL);
	ft_putchar('\n');
  	printf("conversion of go: %p\n", &"go");
	ft_printf("conversion of go: %p\n", &"go");
	ft_putchar('\n');
	printf("The address of a is: %5p\n", (void *) 0);
	ft_printf("The address of a is: %5p\n", (void *) 0);
	ft_putchar('\n');
	printf("The address of a is: %5p\n", (void *) 2);
	ft_printf("The address of a is: %5p\n", (void *) 2);
	ft_putchar('\n');
  	printf("The address of a is: %-5p %c\n", (void *) 2, '.');
	ft_printf("The address of a is: %-5p %c\n",(void *) 2, '.');
	ft_putchar('\n');
	ft_putchar('\n');

	printf("---------------------- UINT ----------------------------- \n");
	ft_putchar('\n');
	printf("pf no flags: %u\n", 153);
	ft_printf("me no flags: %u\n", 153);
	ft_putchar('\n');
	printf("pf width: %5u\n", 153);
    ft_printf("me width: %5u\n", 153);
	ft_putchar('\n');
    printf("pf precision: %.5u\n", 153);
    ft_printf("me precision: %.5u\n", 153);
	ft_putchar('\n');
    printf("pf zero: %07u\n", 153);
    ft_printf("me zero: %07u\n", 153);
	ft_putchar('\n');
   	printf("pf minus: %-5u %c\n", 153, '.');
    ft_printf("me minus: %-5u %c\n", 153, '.');
	ft_putchar('\n');
	ft_putchar('\n');

	
	printf("---------------------- THE END ----------------------------- \n");

	ft_putchar('\n');
	system("leaks test");
	return 0;
}
